/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Public health probe. Returns 200 with service status and version. Not under /api/v1 — served directly at /healthz.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Public endpoint. Authenticates with email + password, mints a session, and sets the __Host-qovira_session (HttpOnly) and qovira_csrf (readable) cookies. The session token is never returned in the body.
         */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Log out (current session)
         * @description Invalidates the current session and clears both auth cookies.
         */
        delete: operations["deleteAuthSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Log out (all sessions)
         * @description Invalidates all sessions for the current user and clears auth cookies.
         */
        delete: operations["deleteAuthSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update current user profile
         * @description Merge-patch semantics: present fields are set, absent fields unchanged. null is not accepted (use an explicit empty string if you need to clear).
         */
        patch: operations["patchMe"];
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password */
        post: operations["postMePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List conversations (cursor-paginated, most-recently-active first)
         * @description Returns a cursor-paginated list of the caller's conversations ordered by most-recently-active first (updated_at DESC, id DESC). Each item includes an opaque preview derived from the first user message in the conversation, truncated to ~80 characters. Unknown query parameters are rejected with 400 unknown_query_param.
         */
        get: operations["listConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get conversation history
         * @description Returns the full chronological message history for the conversation. Returns 404 when the conversation does not exist or belongs to another user.
         */
        get: operations["getConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message to a conversation
         * @description Persists the user message and returns 202 immediately with the persisted message body. The AI response streams over the /events SSE channel tagged by conversationId — the turn outlives this request.
         */
        post: operations["postConversationMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/confirmations/{callId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve a pending tool confirmation
         * @description Approve or deny a pending tool call confirmation. Returns 202 with no body. The harness re-enters the turn asynchronously via SSE.
         */
        post: operations["postConversationConfirmation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reminders (cursor-paginated)
         * @description Returns a cursor-paginated list of reminders. Unknown query parameters are rejected with 400 unknown_query_param.
         */
        get: operations["listReminders"];
        put?: never;
        /** Create a reminder */
        post: operations["postReminder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reminders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a reminder by ID */
        get: operations["getReminder"];
        put?: never;
        post?: never;
        /** Delete a reminder */
        delete: operations["deleteReminder"];
        options?: never;
        head?: never;
        /**
         * Update a reminder
         * @description Merge-patch semantics: present fields are set, absent fields unchanged. null explicitly clears a nullable field (notes, rrule). `status` field routes to complete/reopen logic.
         */
        patch: operations["patchReminder"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /**
             * Format: uri
             * @description Stable URL identifying the problem kind. Always "https://qovira.ai/errors/" + code.
             * @example https://qovira.ai/errors/not_found
             */
            type: string;
            /**
             * @description Short, stable, human-readable summary of the problem type.
             * @example Not found
             */
            title: string;
            /**
             * @description HTTP status code; matches the response status line.
             * @example 404
             */
            status: number;
            /**
             * @description Human-readable explanation specific to this occurrence.
             * @example The requested resource was not found.
             */
            detail: string;
            /**
             * @description Snake_case machine slug; the primary client branching key.
             * @example not_found
             */
            code: string;
            /**
             * @description Correlation ID tying this response to server logs. Always present; sentinel "unknown" if none in context.
             * @example a1b2c3d4e5f6
             */
            requestId: string;
            /** @description Per-field validation errors. Present on 422 only. */
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            /**
             * @description RFC 6901 JSON Pointer to the offending field.
             * @example /email
             */
            pointer: string;
            /**
             * @description Human-readable explanation of why the value is invalid.
             * @example must be a valid email address
             */
            detail: string;
        };
        User: {
            /** @description Opaque user identifier. */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            role: string;
            /** @description IANA timezone name (e.g. "America/New_York"). */
            timezone: string;
            /** @description BCP 47 locale tag (e.g. "en-US"). */
            locale: string;
            /** @description BCP 47 language tag (e.g. "en"). */
            language: string;
        };
        Reminder: {
            id: string;
            userId: string;
            title: string;
            /** @description Optional free-text notes. Absent when not set. */
            notes?: string;
            /**
             * Format: date-time
             * @description RFC 3339 UTC timestamp of when the reminder is due.
             */
            dueAt: string;
            /** @description RFC 5545 RRULE string for recurring reminders. Absent for one-shot. */
            rrule?: string;
            /** @description Snapshotted IANA timezone. NOTE: field name is `tz` (not `timezone`) to distinguish from User.timezone. */
            tz: string;
            /** @description When true (the default), firing the reminder automatically completes it. When false, firing leaves status active (used for recurring reminders that fire but stay active until the user completes them manually). */
            autoComplete: boolean;
            /** @enum {string} */
            status: "active" | "completed";
            /**
             * Format: date-time
             * @description RFC 3339 UTC timestamp. Absent when status != completed.
             */
            completedAt?: string;
            /**
             * Format: date-time
             * @description RFC 3339 UTC timestamp of last fire. Absent until first fire.
             */
            lastFiredAt?: string;
            /** @description Internal scheduler job ID. Absent until scheduled. */
            fireJobId?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Conversation: {
            /** @description Opaque conversation identifier. */
            id: string;
            /** @description First user message truncated to ~80 characters. Empty string when no user message exists yet. */
            preview: string;
            /**
             * Format: date-time
             * @description RFC 3339 UTC timestamp of when the conversation was created.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description RFC 3339 UTC timestamp of the most recent activity.
             */
            updatedAt: string;
        };
        HistoryMessage: {
            /** @description Opaque message identifier. */
            id: string;
            /** @description Message role — one of user, assistant, tool, system. */
            role: string;
            /** @description Message content. For tool messages this is a JSON string. */
            content: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Present on assistant messages that triggered tool calls. Absent otherwise. */
            toolCalls?: {
                [key: string]: unknown;
            }[];
            /** @description Present on tool-result messages. References the callId of the originating tool call. Absent otherwise. */
            toolCallId?: string;
            /** @description Model finish reason (stop, tool_calls, length, etc.). Present on completed assistant messages. Absent otherwise. */
            finishReason?: string;
            /** @description True when this assistant message was abandoned because its pending tool confirmation expired. Such messages are inert and must not be treated as outstanding work. */
            abandoned: boolean;
        };
        ConversationHistory: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            messages: components["schemas"]["HistoryMessage"][];
        };
        MessageResponse: {
            id: string;
            conversationId: string;
            role: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        Pagination: {
            /** @description Opaque cursor for the next page. null when no more pages. */
            nextCursor: string | null;
            hasMore: boolean;
        };
    };
    responses: {
        /** @description Authentication required (unauthenticated or invalid_credentials). */
        ProblemUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description CSRF validation failed (csrf_failed). */
        ProblemForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found. */
        ProblemNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Conflict (e.g. confirmation already resolved or expired). */
        ProblemConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Validation error (validation_error, validation_failed, invalid_decision). */
        ProblemUnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Malformed body or unknown query parameter. */
        ProblemBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Internal server error (internal_error). */
        ProblemInternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                        /** @example 0.1.0 */
                        version: string;
                    };
                };
            };
        };
    };
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Authentication successful. Cookies are set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: date-time
                         * @description RFC 3339 session expiry timestamp.
                         */
                        expiresAt: string;
                        user: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["ProblemUnauthorized"];
            422: components["responses"]["ProblemUnprocessableEntity"];
        };
    };
    deleteAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ProblemUnauthorized"];
            403: components["responses"]["ProblemForbidden"];
        };
    };
    deleteAuthSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All sessions cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ProblemUnauthorized"];
            403: components["responses"]["ProblemForbidden"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["ProblemUnauthorized"];
        };
    };
    patchMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName?: string;
                    timezone?: string;
                    locale?: string;
                    language?: string;
                };
            };
        };
        responses: {
            /** @description Updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["ProblemUnauthorized"];
            403: components["responses"]["ProblemForbidden"];
            422: components["responses"]["ProblemUnprocessableEntity"];
        };
    };
    postMePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    currentPassword: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Password changed successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ProblemUnauthorized"];
            403: components["responses"]["ProblemForbidden"];
            422: components["responses"]["ProblemUnprocessableEntity"];
        };
    };
    listConversations: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor from a previous response's nextCursor field. */
                cursor?: string;
                /** @description Page size (default 25, max 100). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of conversations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Conversation"][];
                        pagination: components["schemas"]["Pagination"];
                    };
                };
            };
            400: components["responses"]["ProblemBadRequest"];
            401: components["responses"]["ProblemUnauthorized"];
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation ID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation with full message history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationHistory"];
                };
            };
            401: components["responses"]["ProblemUnauthorized"];
            404: components["responses"]["ProblemNotFound"];
        };
    };
    postConversationMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation ID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                };
            };
        };
        responses: {
            /** @description Message persisted. AI response will stream over SSE. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["ProblemUnauthorized"];
            403: components["responses"]["ProblemForbidden"];
            404: components["responses"]["ProblemNotFound"];
        };
    };
    postConversationConfirmation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation ID. */
                id: string;
                /** @description Pending confirmation call ID. */
                callId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "approve" | "deny";
                };
            };
        };
        responses: {
            /** @description Decision recorded. No body. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ProblemUnauthorized"];
            403: components["responses"]["ProblemForbidden"];
            404: components["responses"]["ProblemNotFound"];
            409: components["responses"]["ProblemConflict"];
            422: components["responses"]["ProblemUnprocessableEntity"];
        };
    };
    listReminders: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor from a previous response. */
                cursor?: string;
                /** @description Page size (default 25, max 100). */
                limit?: number;
                /** @description Filter by reminder status. */
                status?: "active" | "completed";
                /** @description Filter reminders due before this RFC 3339 timestamp. */
                dueBefore?: string;
                /** @description Filter reminders due after this RFC 3339 timestamp. */
                dueAfter?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of reminders. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Reminder"][];
                        pagination: components["schemas"]["Pagination"];
                    };
                };
            };
            400: components["responses"]["ProblemBadRequest"];
            401: components["responses"]["ProblemUnauthorized"];
        };
    };
    postReminder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    /** @description Optional free-text notes. */
                    notes?: string;
                    /**
                     * Format: date-time
                     * @description RFC 3339 UTC timestamp.
                     */
                    dueAt: string;
                    /** @description IANA timezone (defaults to user's profile timezone). */
                    tz?: string;
                    /**
                     * @description Whether to auto-complete on fire.
                     * @default true
                     */
                    autoComplete?: boolean;
                    /** @description RFC 5545 RRULE for recurring reminders. */
                    rrule?: string;
                };
            };
        };
        responses: {
            /** @description Reminder created. */
            201: {
                headers: {
                    /** @description /api/v1/reminders/{id} */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            400: components["responses"]["ProblemBadRequest"];
            401: components["responses"]["ProblemUnauthorized"];
            403: components["responses"]["ProblemForbidden"];
            422: components["responses"]["ProblemUnprocessableEntity"];
        };
    };
    getReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The reminder. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            401: components["responses"]["ProblemUnauthorized"];
            404: components["responses"]["ProblemNotFound"];
        };
    };
    deleteReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminder deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ProblemUnauthorized"];
            403: components["responses"]["ProblemForbidden"];
            404: components["responses"]["ProblemNotFound"];
        };
    };
    patchReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    /** @description null clears the notes field. */
                    notes?: string | null;
                    /** Format: date-time */
                    dueAt?: string;
                    /** @description null clears the rrule (makes it one-shot). */
                    rrule?: string | null;
                    autoComplete?: boolean;
                    /** @enum {string} */
                    status?: "active" | "completed";
                };
            };
        };
        responses: {
            /** @description Updated reminder. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            401: components["responses"]["ProblemUnauthorized"];
            403: components["responses"]["ProblemForbidden"];
            404: components["responses"]["ProblemNotFound"];
            422: components["responses"]["ProblemUnprocessableEntity"];
        };
    };
}
