// Package id provides monotonic ULID generation for qovira entities.
//
// ULIDs are 26-character Crockford base32 strings that are lexicographically sortable and opaque over the public API.
// All ids generated by this package are strictly increasing, even within the same millisecond (monotonic).
//
// The simplest usage is the package-level [New] function:
//
//	entityID := id.New()
//
// When an injectable generator is needed (e.g. in tests), use [NewGenerator]:
//
//	g := id.NewGenerator()
//	entityID := g.New()
package id

import (
	"crypto/rand"
	"sync"
	"time"

	"github.com/oklog/ulid/v2"
)

// Generator is a thread-safe monotonic ULID source.  Use [NewGenerator] to construct one.  The zero value is not valid;
// always construct via the constructor.
type Generator struct {
	mu      sync.Mutex
	entropy *ulid.MonotonicEntropy
}

// NewGenerator returns a new Generator backed by a crypto/rand monotonic entropy source.  The returned Generator is
// safe for concurrent use by multiple goroutines.
func NewGenerator() *Generator {
	return &Generator{
		// ulid.Monotonic guarantees that ids sharing a millisecond are strictly increasing: each id's entropy is
		// the previous value plus a random step.  Passing inc == 0 selects the library default maximum step
		// (math.MaxUint32); the 80-bit entropy space makes overflow within a single millisecond a practical
		// non-issue at our id-generation rates.
		entropy: ulid.Monotonic(rand.Reader, 0),
	}
}

// New generates and returns a new monotonic ULID as a 26-character Crockford base32 string.  It is safe for concurrent
// use.
func (g *Generator) New() string {
	g.mu.Lock()
	// Both the timestamp sample and the entropy read must happen inside the critical section so that the monotonic
	// sequence is unbroken across goroutines.
	id := ulid.MustNew(ulid.Timestamp(time.Now()), g.entropy)
	g.mu.Unlock()
	return id.String()
}

// defaultGenerator is the package-level generator used by [New].
var defaultGenerator = NewGenerator()

// New generates and returns a new monotonic ULID as a 26-character Crockford base32 string using the package-level
// generator.  It is safe for concurrent use.
func New() string {
	return defaultGenerator.New()
}
