// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"
	"database/sql"
)

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, summary, created_at, updated_at
FROM conversations
WHERE id = ?1
  AND user_id = ?2
`

type GetConversationParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT
    c.id,
    c.created_at,
    c.updated_at,
    COALESCE((
        SELECT m.content
        FROM messages m
        WHERE m.conversation_id = c.id
          AND m.user_id = ?1
          AND m.role = 'user'
        ORDER BY m.created_at, m.id
        LIMIT 1
    ), '') AS preview
FROM conversations c
WHERE c.user_id = ?1
  AND (
      ?2 IS NULL
      OR c.updated_at < ?2
      OR (c.updated_at = ?2 AND c.id < ?3)
  )
ORDER BY c.updated_at DESC, c.id DESC
LIMIT ?4
`

type ListConversationsParams struct {
	UserID          string
	CursorUpdatedAt interface{}
	CursorID        sql.NullString
	Limit           int64
}

type ListConversationsRow struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Preview   interface{}
}

// List conversations for a user, keyset-paginated on (updated_at DESC, id DESC)
// so the most-recently-active conversation appears first. Fetches limit+1 rows so
// the caller can detect whether a next page exists.
//
// preview is derived via a correlated subquery that finds the first user message
// in the conversation (ORDER BY created_at, id LIMIT 1). The subquery carries its
// own user_id predicate so the scope guard accepts it without an exemption. preview
// is empty when no user message exists yet.
//
// The keyset predicate uses the expanded tuple form (required because sqlc's SQLite
// parser does not support row-value syntax): the cursor marks the last seen
// (updated_at, id) pair and we skip rows that sort before it in the DESC order.
// Equivalent to: (updated_at, id) < (cursor_updated_at, cursor_id) in DESC order,
// which expands to:
//
//	updated_at < cursor OR (updated_at = cursor AND id < cursor_id).
//
// MANDATORY user_id predicate on conversations enforced by scope guard.
func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversations,
		arg.UserID,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Preview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations
SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?1
  AND user_id = ?2
`

type TouchConversationParams struct {
	ID     string
	UserID string
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.ExecContext(ctx, touchConversation, arg.ID, arg.UserID)
	return err
}

const upsertConversation = `-- name: UpsertConversation :exec

INSERT INTO conversations (id, user_id, created_at, updated_at)
VALUES (?1, ?2, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
ON CONFLICT (id) DO NOTHING
`

type UpsertConversationParams struct {
	ID     string
	UserID string
}

// Queries for the conversations table.
// Every SELECT/UPDATE/DELETE includes a user_id predicate so the row always
// belongs to the bound Scope. Parameters use sqlc named params (@name).
// Insert-if-new only. The store wrapper (conversations.go) enforces ownership by
// calling GetConversation immediately after: if the INSERT no-opped because the id
// belongs to another user, GetConversation (user-scoped) returns sql.ErrNoRows,
// which is mapped to ErrConversationNotOwned. When the caller re-posts to their
// own conversation, GetConversation finds the row and TouchConversation bumps
// updated_at. This three-step protocol is safe because the write pool is capped at
// one connection, serialising all writes and eliminating TOCTOU races.
func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) error {
	_, err := q.db.ExecContext(ctx, upsertConversation, arg.ID, arg.UserID)
	return err
}
