// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"
)

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, summary, created_at, updated_at
FROM conversations
WHERE id = ?1
  AND user_id = ?2
`

type GetConversationParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations
SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?1
  AND user_id = ?2
`

type TouchConversationParams struct {
	ID     string
	UserID string
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.ExecContext(ctx, touchConversation, arg.ID, arg.UserID)
	return err
}

const upsertConversation = `-- name: UpsertConversation :exec

INSERT INTO conversations (id, user_id, created_at, updated_at)
VALUES (?1, ?2, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
ON CONFLICT (id) DO NOTHING
`

type UpsertConversationParams struct {
	ID     string
	UserID string
}

// Queries for the conversations table.
// Every SELECT/UPDATE/DELETE includes a user_id predicate so the row always
// belongs to the bound Scope. Parameters use sqlc named params (@name).
// Insert-if-new only. The store wrapper (conversations.go) enforces ownership by
// calling GetConversation immediately after: if the INSERT no-opped because the id
// belongs to another user, GetConversation (user-scoped) returns sql.ErrNoRows,
// which is mapped to ErrConversationNotOwned. When the caller re-posts to their
// own conversation, GetConversation finds the row and TouchConversation bumps
// updated_at. This three-step protocol is safe because the write pool is capped at
// one connection, serialising all writes and eliminating TOCTOU races.
func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) error {
	_, err := q.db.ExecContext(ctx, upsertConversation, arg.ID, arg.UserID)
	return err
}
