// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package db

import (
	"context"
)

const getInstance = `-- name: GetInstance :one
SELECT id, created_at FROM instance WHERE id = 1
`

func (q *Queries) GetInstance(ctx context.Context) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstance)
	var i Instance
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
