// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
)

const advanceRecurringJob = `-- name: AdvanceRecurringJob :execrows
UPDATE jobs
SET status = 'pending', run_at = ?1, locked_at = NULL, attempt = 0, updated_at = ?2
WHERE id = ?3 AND status = 'running'
`

type AdvanceRecurringJobParams struct {
	RunAt     string
	UpdatedAt string
	ID        string
}

// scopeguard:allow-unscoped: SYSTEM ENGINE -- the scheduler self-reschedules a recurring job after its handler
// succeeds: resets status to 'pending', sets run_at to the next occurrence, clears locked_at, and resets
// attempt to 0. Only updates rows with status = 'running' (the job the scheduler just leased) to guard against a
// future double-processor. A 0-row result (e.g. the row was deleted by Cancel) is harmless and silently
// tolerated by the caller.
func (q *Queries) AdvanceRecurringJob(ctx context.Context, arg AdvanceRecurringJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceRecurringJob, arg.RunAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deadLetterJob = `-- name: DeadLetterJob :execrows
UPDATE jobs SET status = 'failed', last_error = ?1, locked_at = NULL, updated_at = ?2
WHERE id = ?3 AND status = 'running'
`

type DeadLetterJobParams struct {
	LastError sql.NullString
	UpdatedAt string
	ID        string
}

// scopeguard:allow-unscoped: SYSTEM ENGINE -- the scheduler marks an exhausted job as permanently failed. Sets
// status='failed', records last_error, and clears locked_at. The row is intentionally kept (NOT deleted) so
// operators can inspect dead-lettered jobs. AND status = 'running' ensures the update only applies to rows the
// scheduler actually leased, guarding against a future double-processor. A 0-row result (e.g. the row was
// already deleted by Cancel) is harmless and silently tolerated by the caller.
func (q *Queries) DeadLetterJob(ctx context.Context, arg DeadLetterJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deadLetterJob, arg.LastError, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = ?1
`

// scopeguard:allow-unscoped: SYSTEM ENGINE -- the scheduler deletes the row after a handler succeeds. The
// scheduler owns the row lifecycle; no user_id predicate is applicable.
func (q *Queries) DeleteJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getJobIDByKey = `-- name: GetJobIDByKey :one

SELECT id FROM jobs WHERE key = ?1
`

// Queries for the jobs table (durable scheduler queue).
// The scheduler accesses jobs cross-user: the claim selects due jobs across ALL users and resolves scope per-row.
// This is intentionally unscoped -- each query below carries an explicit scopeguard annotation with the reason.
//
// Parameters use sqlc named params (@name) per the house convention.
//
// NOTE: Several operations use raw SQL via s.Writer() rather than sqlc queries, because sqlc's SQLite ANTLR
// parser cannot model the required shapes:
//  1. INSERT ... ON CONFLICT(key) DO NOTHING: the upsert clause is not supported.
//  2. UPDATE ... WHERE id IN (SELECT ... LIMIT @batch) RETURNING ...: compound UPDATE.
//
// These are executed as s.Writer().ExecContext / QueryContext in internal/scheduler.
// scopeguard:allow-unscoped: cross-user lookup by idempotency key. The scheduler resolves the existing job id
// when ON CONFLICT(key) DO NOTHING suppresses the insert.
func (q *Queries) GetJobIDByKey(ctx context.Context, key sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, getJobIDByKey, key)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getJobStatus = `-- name: GetJobStatus :one
SELECT status FROM jobs WHERE id = ?1
`

// scopeguard:allow-unscoped: SYSTEM ENGINE -- the scheduler reads the status of any job regardless of owner to
// implement Cancel/Reschedule atomicity. Called inside a transaction on the write pool to provide a consistent
// read-then-write with no TOCTOU window.
func (q *Queries) GetJobStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getJobStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const reclaimStaleJobs = `-- name: ReclaimStaleJobs :execrows
UPDATE jobs SET status = 'pending', locked_at = NULL, updated_at = ?1
WHERE status = 'running' AND locked_at IS NOT NULL AND locked_at < ?2
`

type ReclaimStaleJobsParams struct {
	UpdatedAt string
	Threshold sql.NullString
}

// scopeguard:allow-unscoped: SYSTEM ENGINE -- cross-user reclaim sweep. The scheduler reclaims running rows
// whose locked_at is older than the lease threshold, returning them to pending so they can be re-leased. This
// fires on boot (to recover rows orphaned by a prior process crash) and on each poll tick (to recover
// wedged-but-alive workers that ignore cancellation). The locked_at comparison uses RFC3339 UTC strings, which are
// lexicographically ordered, matching the pattern used by the claim query's run_at comparison. attempt is
// deliberately NOT reset: the retry ceiling must still apply to reclaimed jobs.
func (q *Queries) ReclaimStaleJobs(ctx context.Context, arg ReclaimStaleJobsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reclaimStaleJobs, arg.UpdatedAt, arg.Threshold)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rescheduleJob = `-- name: RescheduleJob :execrows
UPDATE jobs SET run_at = ?1, updated_at = ?2
WHERE id = ?3 AND status = 'pending'
`

type RescheduleJobParams struct {
	RunAt     string
	UpdatedAt string
	ID        string
}

// scopeguard:allow-unscoped: SYSTEM ENGINE -- the scheduler moves run_at for any pending job. Only updates rows
// with status='pending'; returns 0 rows affected when the job is not pending (running or absent today;
// 'failed'/dead-letter is a later slice). The caller interprets a non-pending status as ErrJobRunning or
// ErrJobNotFound after reading the status inside the enclosing transaction.
func (q *Queries) RescheduleJob(ctx context.Context, arg RescheduleJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rescheduleJob, arg.RunAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs SET status = 'pending', run_at = ?1, locked_at = NULL, updated_at = ?2
WHERE id = ?3 AND status = 'running'
`

type RetryJobParams struct {
	RunAt     string
	UpdatedAt string
	ID        string
}

// scopeguard:allow-unscoped: SYSTEM ENGINE -- the scheduler re-arms a failed job row for retry with a backoff
// run_at. Sets status='pending', clears locked_at, and advances run_at so the job re-enters the claim queue at
// the calculated backoff time. AND status = 'running' ensures the update only applies to rows the scheduler
// actually leased, guarding against a future double-processor. A 0-row result (e.g. the row was already
// deleted by Cancel) is harmless and silently tolerated by the caller.
func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryJob, arg.RunAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
