// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const insertMessage = `-- name: InsertMessage :one

INSERT INTO messages (id, conversation_id, user_id, role, content, tool_calls, tool_call_id, finish_reason)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
RETURNING id, conversation_id, user_id, role, content, tool_calls, tool_call_id, finish_reason, created_at
`

type InsertMessageParams struct {
	ID             string
	ConversationID string
	UserID         string
	Role           string
	Content        string
	ToolCalls      sql.NullString
	ToolCallID     sql.NullString
	FinishReason   sql.NullString
}

// Queries for the messages table.
// Every SELECT/UPDATE/DELETE includes a user_id predicate so the row always
// belongs to the bound Scope. Parameters use sqlc named params (@name).
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.UserID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolCallID,
		arg.FinishReason,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.FinishReason,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, user_id, role, content, tool_calls, tool_call_id, finish_reason, created_at
FROM messages
WHERE conversation_id = ?1
  AND user_id = ?2
ORDER BY created_at
`

type ListMessagesParams struct {
	ConversationID string
	UserID         string
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.FinishReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
