// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Conversation struct {
	ID        string
	UserID    string
	Summary   sql.NullString
	CreatedAt string
	UpdatedAt string
}

type Instance struct {
	ID        int64
	CreatedAt string
}

type Message struct {
	ID             string
	ConversationID string
	UserID         string
	Role           string
	Content        string
	ToolCalls      sql.NullString
	ToolCallID     sql.NullString
	FinishReason   sql.NullString
	CreatedAt      string
}

type Session struct {
	ID         string
	UserID     string
	TokenHash  []byte
	CreatedAt  string
	LastUsedAt string
}

type Setting struct {
	SettingKey string
	Value      string
	UpdatedAt  string
}

type User struct {
	ID           string
	Email        string
	DisplayName  string
	PasswordHash string
	Role         string
	Timezone     string
	Locale       string
	Language     string
	CreatedAt    string
	UpdatedAt    string
}

type UserDatum struct {
	ID        string
	UserID    string
	Value     string
	CreatedAt string
}
