// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Conversation struct {
	ID        string
	UserID    string
	Summary   sql.NullString
	CreatedAt string
	UpdatedAt string
}

type Instance struct {
	ID        int64
	CreatedAt string
}

type Job struct {
	ID           string
	Key          sql.NullString
	Kind         string
	Payload      string
	UserID       sql.NullString
	Status       string
	RunAt        string
	Attempt      int64
	LockedAt     sql.NullString
	Rrule        sql.NullString
	Tz           sql.NullString
	IntervalSecs sql.NullInt64
	LastError    sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

type Message struct {
	ID             string
	ConversationID string
	UserID         string
	Role           string
	Content        string
	ToolCalls      sql.NullString
	ToolCallID     sql.NullString
	FinishReason   sql.NullString
	CreatedAt      string
	Abandoned      int64
}

type PendingConfirmation struct {
	ID             string
	ConversationID string
	MessageID      string
	UserID         string
	ToolName       string
	Args           string
	Risk           string
	Status         string
	CreatedAt      string
	ExpiresAt      string
}

type Session struct {
	ID         string
	UserID     string
	TokenHash  []byte
	CreatedAt  string
	LastUsedAt string
}

type Setting struct {
	SettingKey string
	Value      string
	UpdatedAt  string
}

type User struct {
	ID           string
	Email        string
	DisplayName  string
	PasswordHash string
	Role         string
	Timezone     string
	Locale       string
	Language     string
	CreatedAt    string
	UpdatedAt    string
}

type UserDatum struct {
	ID        string
	UserID    string
	Value     string
	CreatedAt string
}
