// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Instance struct {
	ID        int64
	CreatedAt string
}

type Setting struct {
	SettingKey string
	Value      string
	UpdatedAt  string
}

type User struct {
	ID           string
	Email        string
	DisplayName  string
	PasswordHash string
	Role         string
	Timezone     string
	Locale       string
	Language     string
	CreatedAt    string
	UpdatedAt    string
}

type UserDatum struct {
	ID        string
	UserID    string
	Value     string
	CreatedAt string
}
