// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_confirmations.sql

package db

import (
	"context"
)

const countNonExpiredConfirmationsByMessageID = `-- name: CountNonExpiredConfirmationsByMessageID :one
SELECT count(*)
FROM pending_confirmations
WHERE message_id = ?1
  AND user_id = ?2
  AND status != 'expired'
`

type CountNonExpiredConfirmationsByMessageIDParams struct {
	MessageID string
	UserID    string
}

// Returns the count of pending_confirmations rows for a given assistant message
// that are NOT in 'expired' status (i.e. 'pending', 'approved', or 'denied').
// Used to gate MarkMessageAbandoned: the assistant message is only abandoned when
// this count is zero (no siblings remain pending or were resolved by the user).
// User-scoped: requires user_id to prevent cross-user information leakage.
func (q *Queries) CountNonExpiredConfirmationsByMessageID(ctx context.Context, arg CountNonExpiredConfirmationsByMessageIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNonExpiredConfirmationsByMessageID, arg.MessageID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPendingConfirmation = `-- name: GetPendingConfirmation :one
SELECT id, conversation_id, message_id, user_id, tool_name, args, risk, status, created_at, expires_at
FROM pending_confirmations
WHERE id = ?1
  AND user_id = ?2
`

type GetPendingConfirmationParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetPendingConfirmation(ctx context.Context, arg GetPendingConfirmationParams) (PendingConfirmation, error) {
	row := q.db.QueryRowContext(ctx, getPendingConfirmation, arg.ID, arg.UserID)
	var i PendingConfirmation
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.UserID,
		&i.ToolName,
		&i.Args,
		&i.Risk,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertPendingConfirmation = `-- name: InsertPendingConfirmation :one

INSERT INTO pending_confirmations (id, conversation_id, message_id, user_id, tool_name, args, risk, status, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
RETURNING id, conversation_id, message_id, user_id, tool_name, args, risk, status, created_at, expires_at
`

type InsertPendingConfirmationParams struct {
	ID             string
	ConversationID string
	MessageID      string
	UserID         string
	ToolName       string
	Args           string
	Risk           string
	Status         string
	ExpiresAt      string
}

// Queries for the pending_confirmations table.
// Every SELECT/UPDATE includes a user_id predicate so the row always
// belongs to the bound Scope. Parameters use sqlc named params (@name).
func (q *Queries) InsertPendingConfirmation(ctx context.Context, arg InsertPendingConfirmationParams) (PendingConfirmation, error) {
	row := q.db.QueryRowContext(ctx, insertPendingConfirmation,
		arg.ID,
		arg.ConversationID,
		arg.MessageID,
		arg.UserID,
		arg.ToolName,
		arg.Args,
		arg.Risk,
		arg.Status,
		arg.ExpiresAt,
	)
	var i PendingConfirmation
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.UserID,
		&i.ToolName,
		&i.Args,
		&i.Risk,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listLapsedConfirmations = `-- name: ListLapsedConfirmations :many
SELECT id, conversation_id, message_id, user_id, tool_name, args, risk, status, created_at, expires_at
FROM pending_confirmations
WHERE status = 'pending'
  AND expires_at < ?1
ORDER BY expires_at, id
`

// scopeguard:allow-unscoped: SYSTEM-HOUSEKEEPING cross-user sweep. The scheduler
// calls SweepExpiredConfirmations across all users by TTL cutoff, so no single
// user_id predicate is applicable. Each returned row carries its own user_id so
// the caller can scope per-row operations (abandon message, emit per-user event).
func (q *Queries) ListLapsedConfirmations(ctx context.Context, now string) ([]PendingConfirmation, error) {
	rows, err := q.db.QueryContext(ctx, listLapsedConfirmations, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingConfirmation
	for rows.Next() {
		var i PendingConfirmation
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.MessageID,
			&i.UserID,
			&i.ToolName,
			&i.Args,
			&i.Risk,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConfirmationExpired = `-- name: MarkConfirmationExpired :execrows
UPDATE pending_confirmations
SET status = 'expired'
WHERE id = ?1
  AND user_id = ?2
  AND status = 'pending'
`

type MarkConfirmationExpiredParams struct {
	ID     string
	UserID string
}

// Atomic CAS: transitions a pending row to expired only when still pending.
// Used by both the lazy check (user-scoped, includes user_id) and the sweep
// (system-scope, but calls this per-row with the row's user_id from ListLapsedConfirmations).
func (q *Queries) MarkConfirmationExpired(ctx context.Context, arg MarkConfirmationExpiredParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markConfirmationExpired, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePendingConfirmationStatusIfCurrent = `-- name: UpdatePendingConfirmationStatusIfCurrent :execrows
UPDATE pending_confirmations
SET status = ?1
WHERE id = ?2
  AND user_id = ?3
  AND status = 'pending'
  AND NOT (expires_at < ?4)
`

type UpdatePendingConfirmationStatusIfCurrentParams struct {
	Status string
	ID     string
	UserID string
	Now    string
}

func (q *Queries) UpdatePendingConfirmationStatusIfCurrent(ctx context.Context, arg UpdatePendingConfirmationStatusIfCurrentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePendingConfirmationStatusIfCurrent,
		arg.Status,
		arg.ID,
		arg.UserID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
