// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_confirmations.sql

package db

import (
	"context"
)

const getPendingConfirmation = `-- name: GetPendingConfirmation :one
SELECT id, conversation_id, message_id, user_id, tool_name, args, risk, status, created_at, expires_at
FROM pending_confirmations
WHERE id = ?1
  AND user_id = ?2
`

type GetPendingConfirmationParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetPendingConfirmation(ctx context.Context, arg GetPendingConfirmationParams) (PendingConfirmation, error) {
	row := q.db.QueryRowContext(ctx, getPendingConfirmation, arg.ID, arg.UserID)
	var i PendingConfirmation
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.UserID,
		&i.ToolName,
		&i.Args,
		&i.Risk,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertPendingConfirmation = `-- name: InsertPendingConfirmation :one

INSERT INTO pending_confirmations (id, conversation_id, message_id, user_id, tool_name, args, risk, status, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
RETURNING id, conversation_id, message_id, user_id, tool_name, args, risk, status, created_at, expires_at
`

type InsertPendingConfirmationParams struct {
	ID             string
	ConversationID string
	MessageID      string
	UserID         string
	ToolName       string
	Args           string
	Risk           string
	Status         string
	ExpiresAt      string
}

// Queries for the pending_confirmations table.
// Every SELECT/UPDATE includes a user_id predicate so the row always
// belongs to the bound Scope. Parameters use sqlc named params (@name).
func (q *Queries) InsertPendingConfirmation(ctx context.Context, arg InsertPendingConfirmationParams) (PendingConfirmation, error) {
	row := q.db.QueryRowContext(ctx, insertPendingConfirmation,
		arg.ID,
		arg.ConversationID,
		arg.MessageID,
		arg.UserID,
		arg.ToolName,
		arg.Args,
		arg.Risk,
		arg.Status,
		arg.ExpiresAt,
	)
	var i PendingConfirmation
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.UserID,
		&i.ToolName,
		&i.Args,
		&i.Risk,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listPendingConfirmationsByConversation = `-- name: ListPendingConfirmationsByConversation :many
SELECT id, conversation_id, message_id, user_id, tool_name, args, risk, status, created_at, expires_at
FROM pending_confirmations
WHERE conversation_id = ?1
  AND user_id = ?2
ORDER BY created_at, id
`

type ListPendingConfirmationsByConversationParams struct {
	ConversationID string
	UserID         string
}

func (q *Queries) ListPendingConfirmationsByConversation(ctx context.Context, arg ListPendingConfirmationsByConversationParams) ([]PendingConfirmation, error) {
	rows, err := q.db.QueryContext(ctx, listPendingConfirmationsByConversation, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingConfirmation
	for rows.Next() {
		var i PendingConfirmation
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.MessageID,
			&i.UserID,
			&i.ToolName,
			&i.Args,
			&i.Risk,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePendingConfirmationStatus = `-- name: UpdatePendingConfirmationStatus :execrows
UPDATE pending_confirmations
SET status = ?1
WHERE id = ?2
  AND user_id = ?3
  AND status = 'pending'
`

type UpdatePendingConfirmationStatusParams struct {
	Status string
	ID     string
	UserID string
}

func (q *Queries) UpdatePendingConfirmationStatus(ctx context.Context, arg UpdatePendingConfirmationStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePendingConfirmationStatus, arg.Status, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
