// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package db

import (
	"context"
	"database/sql"
)

const deleteReminder = `-- name: DeleteReminder :execrows
DELETE FROM reminders
WHERE id      = ?1
  AND user_id = ?2
`

type DeleteReminderParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteReminder(ctx context.Context, arg DeleteReminderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReminder, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getReminder = `-- name: GetReminder :one
SELECT id, user_id, title, notes, due_at, rrule, tz,
       auto_complete, status, completed_at, last_fired_at,
       fire_job_id, created_at, updated_at
FROM reminders
WHERE id = ?1
  AND user_id = ?2
`

type GetReminderParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetReminder(ctx context.Context, arg GetReminderParams) (Reminder, error) {
	row := q.db.QueryRowContext(ctx, getReminder, arg.ID, arg.UserID)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Notes,
		&i.DueAt,
		&i.Rrule,
		&i.Tz,
		&i.AutoComplete,
		&i.Status,
		&i.CompletedAt,
		&i.LastFiredAt,
		&i.FireJobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReminder = `-- name: InsertReminder :exec

INSERT INTO reminders (
    id, user_id, title, notes, due_at, rrule, tz,
    auto_complete, status, completed_at, last_fired_at,
    fire_job_id, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7,
    ?8, ?9, ?10, ?11,
    ?12, ?13, ?14
)
`

type InsertReminderParams struct {
	ID           string
	UserID       string
	Title        string
	Notes        sql.NullString
	DueAt        string
	Rrule        sql.NullString
	Tz           string
	AutoComplete int64
	Status       string
	CompletedAt  sql.NullString
	LastFiredAt  sql.NullString
	FireJobID    sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

// Scoped queries for the reminders table.
// reminders is user-owned: every SELECT/UPDATE/DELETE includes a user_id
// predicate so rows are always confined to the bound Scope.  The CI scope
// guard (TestScopeGuard_RealQueries) enforces this at build time.
//
// Parameters use sqlc named params (@name) per the house convention.
func (q *Queries) InsertReminder(ctx context.Context, arg InsertReminderParams) error {
	_, err := q.db.ExecContext(ctx, insertReminder,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Notes,
		arg.DueAt,
		arg.Rrule,
		arg.Tz,
		arg.AutoComplete,
		arg.Status,
		arg.CompletedAt,
		arg.LastFiredAt,
		arg.FireJobID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const setReminderFireJobID = `-- name: SetReminderFireJobID :execrows
UPDATE reminders
SET fire_job_id = ?1,
    updated_at  = ?2
WHERE id = ?3
  AND user_id = ?4
`

type SetReminderFireJobIDParams struct {
	FireJobID sql.NullString
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) SetReminderFireJobID(ctx context.Context, arg SetReminderFireJobIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setReminderFireJobID,
		arg.FireJobID,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const stampFiredAutoComplete = `-- name: StampFiredAutoComplete :execrows
UPDATE reminders
SET last_fired_at = ?1,
    status        = 'completed',
    completed_at  = ?2,
    updated_at    = ?3
WHERE id = ?4
  AND user_id = ?5
`

type StampFiredAutoCompleteParams struct {
	LastFiredAt sql.NullString
	CompletedAt sql.NullString
	UpdatedAt   string
	ID          string
	UserID      string
}

func (q *Queries) StampFiredAutoComplete(ctx context.Context, arg StampFiredAutoCompleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, stampFiredAutoComplete,
		arg.LastFiredAt,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const stampFiredKeepActive = `-- name: StampFiredKeepActive :execrows
UPDATE reminders
SET last_fired_at = ?1,
    updated_at    = ?2
WHERE id = ?3
  AND user_id = ?4
`

type StampFiredKeepActiveParams struct {
	LastFiredAt sql.NullString
	UpdatedAt   string
	ID          string
	UserID      string
}

func (q *Queries) StampFiredKeepActive(ctx context.Context, arg StampFiredKeepActiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, stampFiredKeepActive,
		arg.LastFiredAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
