// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package db

import (
	"context"
	"database/sql"
)

const countReminders = `-- name: CountReminders :one
SELECT COUNT(*) AS count
FROM reminders
WHERE user_id = ?1
  AND (?2     IS NULL OR status = ?2)
  AND (?3  IS NULL OR due_at > ?3)
  AND (?4 IS NULL OR due_at < ?4)
`

type CountRemindersParams struct {
	UserID    string
	Status    interface{}
	DueAfter  interface{}
	DueBefore interface{}
}

// Count reminders for a user with optional status and due-window filters. Uses the same filter predicates as
// ListReminders so the count is always consistent with what a list query would return. The result is used by the
// list_reminders tool to emit a truncation signal when more than 20 match. MANDATORY user_id predicate enforced by
// scope guard.
func (q *Queries) CountReminders(ctx context.Context, arg CountRemindersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReminders,
		arg.UserID,
		arg.Status,
		arg.DueAfter,
		arg.DueBefore,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteReminder = `-- name: DeleteReminder :execrows
DELETE FROM reminders
WHERE id      = ?1
  AND user_id = ?2
`

type DeleteReminderParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteReminder(ctx context.Context, arg DeleteReminderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReminder, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getReminder = `-- name: GetReminder :one
SELECT id, user_id, title, notes, due_at, rrule, tz,
       auto_complete, status, completed_at, last_fired_at,
       fire_job_id, created_at, updated_at
FROM reminders
WHERE id = ?1
  AND user_id = ?2
`

type GetReminderParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetReminder(ctx context.Context, arg GetReminderParams) (Reminder, error) {
	row := q.db.QueryRowContext(ctx, getReminder, arg.ID, arg.UserID)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Notes,
		&i.DueAt,
		&i.Rrule,
		&i.Tz,
		&i.AutoComplete,
		&i.Status,
		&i.CompletedAt,
		&i.LastFiredAt,
		&i.FireJobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReminder = `-- name: InsertReminder :exec

INSERT INTO reminders (
    id, user_id, title, notes, due_at, rrule, tz,
    auto_complete, status, completed_at, last_fired_at,
    fire_job_id, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7,
    ?8, ?9, ?10, ?11,
    ?12, ?13, ?14
)
`

type InsertReminderParams struct {
	ID           string
	UserID       string
	Title        string
	Notes        sql.NullString
	DueAt        string
	Rrule        sql.NullString
	Tz           string
	AutoComplete int64
	Status       string
	CompletedAt  sql.NullString
	LastFiredAt  sql.NullString
	FireJobID    sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

// Scoped queries for the reminders table.
// reminders is user-owned: every SELECT/UPDATE/DELETE includes a user_id predicate so rows are always
// confined to the bound Scope.  The CI scope guard (TestScopeGuard_RealQueries) enforces this at build time.
//
// Parameters use sqlc named params (@name) per the house convention.
func (q *Queries) InsertReminder(ctx context.Context, arg InsertReminderParams) error {
	_, err := q.db.ExecContext(ctx, insertReminder,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Notes,
		arg.DueAt,
		arg.Rrule,
		arg.Tz,
		arg.AutoComplete,
		arg.Status,
		arg.CompletedAt,
		arg.LastFiredAt,
		arg.FireJobID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listReminders = `-- name: ListReminders :many
SELECT id, user_id, title, notes, due_at, rrule, tz,
       auto_complete, status, completed_at, last_fired_at,
       fire_job_id, created_at, updated_at
FROM reminders
WHERE user_id = ?1
  AND (?2     IS NULL OR status = ?2)
  AND (?3  IS NULL OR due_at > ?3)
  AND (?4 IS NULL OR due_at < ?4)
  AND (?5 IS NULL
       OR due_at > ?5
       OR (due_at = ?5 AND id > ?6))
ORDER BY due_at, id
LIMIT ?7
`

type ListRemindersParams struct {
	UserID    string
	Status    interface{}
	DueAfter  interface{}
	DueBefore interface{}
	CursorDue interface{}
	CursorID  sql.NullString
	Limit     int64
}

// List reminders for a user with optional status and due-window filters, keyset-paginated on (due_at, id).  Fetches
// limit+1 rows so the caller can detect whether a next page exists.
//
// Optional filters use sqlc.narg so absent values are NULL and the predicate becomes a no-op.  The keyset
// predicate uses the expanded form of the tuple comparison (due_at, id) > (cursor_due, cursor_id), which is
// logically identical: skip rows that sort before the cursor.  Both forms produce the same result set; the
// expanded form is required because sqlc's SQLite parser does not recognise the row-value syntax (col, col) > (?, ?).
//
// The query is served by the reminders_user_due index on (user_id, due_at, id). That index satisfies
// ORDER BY due_at, id directly from the index-ordered stream for both the no-status path and the status-filtered
// path (status is a residual predicate).  No USE TEMP B-TREE FOR ORDER BY occurs in either case, verified by
// EXPLAIN QUERY PLAN in TestListReminders_IndexPlan.
func (q *Queries) ListReminders(ctx context.Context, arg ListRemindersParams) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listReminders,
		arg.UserID,
		arg.Status,
		arg.DueAfter,
		arg.DueBefore,
		arg.CursorDue,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Notes,
			&i.DueAt,
			&i.Rrule,
			&i.Tz,
			&i.AutoComplete,
			&i.Status,
			&i.CompletedAt,
			&i.LastFiredAt,
			&i.FireJobID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReminderFireJobID = `-- name: SetReminderFireJobID :execrows
UPDATE reminders
SET fire_job_id = ?1,
    updated_at  = ?2
WHERE id = ?3
  AND user_id = ?4
`

type SetReminderFireJobIDParams struct {
	FireJobID sql.NullString
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) SetReminderFireJobID(ctx context.Context, arg SetReminderFireJobIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setReminderFireJobID,
		arg.FireJobID,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const stampFiredAutoComplete = `-- name: StampFiredAutoComplete :execrows
UPDATE reminders
SET last_fired_at = ?1,
    status        = 'completed',
    completed_at  = ?2,
    updated_at    = ?3
WHERE id = ?4
  AND user_id = ?5
`

type StampFiredAutoCompleteParams struct {
	LastFiredAt sql.NullString
	CompletedAt sql.NullString
	UpdatedAt   string
	ID          string
	UserID      string
}

func (q *Queries) StampFiredAutoComplete(ctx context.Context, arg StampFiredAutoCompleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, stampFiredAutoComplete,
		arg.LastFiredAt,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const stampFiredKeepActive = `-- name: StampFiredKeepActive :execrows
UPDATE reminders
SET last_fired_at = ?1,
    updated_at    = ?2
WHERE id = ?3
  AND user_id = ?4
`

type StampFiredKeepActiveParams struct {
	LastFiredAt sql.NullString
	UpdatedAt   string
	ID          string
	UserID      string
}

func (q *Queries) StampFiredKeepActive(ctx context.Context, arg StampFiredKeepActiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, stampFiredKeepActive,
		arg.LastFiredAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const stampFiredRecurring = `-- name: StampFiredRecurring :execrows
UPDATE reminders
SET last_fired_at = ?1,
    due_at        = ?2,
    updated_at    = ?3
WHERE id = ?4
  AND user_id = ?5
`

type StampFiredRecurringParams struct {
	LastFiredAt sql.NullString
	DueAt       string
	UpdatedAt   string
	ID          string
	UserID      string
}

// Advances a recurring reminder after each fire: stamps last_fired_at, advances due_at to the next occurrence, and
// keeps status=active. Only the fire handler calls this; UpdateReminder intentionally excludes last_fired_at.
func (q *Queries) StampFiredRecurring(ctx context.Context, arg StampFiredRecurringParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, stampFiredRecurring,
		arg.LastFiredAt,
		arg.DueAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateReminder = `-- name: UpdateReminder :execrows
UPDATE reminders
SET title = ?1,
    notes = ?2,
    due_at = ?3,
    rrule = ?4,
    auto_complete = ?5,
    status = ?6,
    completed_at = ?7,
    fire_job_id = ?8,
    updated_at = ?9
WHERE id = ?10
  AND user_id = ?11
`

type UpdateReminderParams struct {
	Title        string
	Notes        sql.NullString
	DueAt        string
	Rrule        sql.NullString
	AutoComplete int64
	Status       string
	CompletedAt  sql.NullString
	FireJobID    sql.NullString
	UpdatedAt    string
	ID           string
	UserID       string
}

// Writes all mutable columns for a single reminder row. last_fired_at is intentionally excluded: the fire
// handler is its sole writer. fire_job_id is included so Service owns all fire-job lifecycle transitions.
// MANDATORY user_id predicate enforced by scope guard.
func (q *Queries) UpdateReminder(ctx context.Context, arg UpdateReminderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateReminder,
		arg.Title,
		arg.Notes,
		arg.DueAt,
		arg.Rrule,
		arg.AutoComplete,
		arg.Status,
		arg.CompletedAt,
		arg.FireJobID,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
