// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const bumpSessionLastUsedByID = `-- name: BumpSessionLastUsedByID :execrows
UPDATE sessions SET last_used_at = ?1 WHERE id = ?2 AND user_id = ?3
`

type BumpSessionLastUsedByIDParams struct {
	LastUsedAt string
	ID         string
	UserID     string
}

func (q *Queries) BumpSessionLastUsedByID(ctx context.Context, arg BumpSessionLastUsedByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bumpSessionLastUsedByID, arg.LastUsedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (id, user_id, token_hash, created_at, last_used_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type CreateSessionParams struct {
	ID         string
	UserID     string
	TokenHash  []byte
	CreatedAt  string
	LastUsedAt string
}

// Queries for the sessions table.
// sessions is per-user data (it has a user_id column and belongs to individual users), but some queries operate on a
// token_hash key (the bearer capability itself) rather than a user_id predicate.  Those queries carry a per-query
// scopeguard exemption with an explicit reason.  The bump query is keyed by id+user_id and needs no annotation.
// INSERT is always scopeguard-exempt.
//
// Parameters use sqlc named params (@name) per the house convention.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}

const deleteOtherSessionsForUser = `-- name: DeleteOtherSessionsForUser :execrows
DELETE FROM sessions
WHERE user_id = ?1
  AND id != ?2
`

type DeleteOtherSessionsForUserParams struct {
	UserID string
	KeepID string
}

func (q *Queries) DeleteOtherSessionsForUser(ctx context.Context, arg DeleteOtherSessionsForUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOtherSessionsForUser, arg.UserID, arg.KeepID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :execrows
DELETE FROM sessions
WHERE token_hash = ?1
`

// scopeguard:allow-unscoped: token_hash is the sha256 of a 256-bit bearer capability that itself authorizes
// access; this path is used for single-session logout and best-effort delete-on-expiry, both keyed by the bearer
// token before a user_id is available.
func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :execrows
DELETE FROM sessions
WHERE user_id = ?1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, created_at, last_used_at
FROM sessions
WHERE token_hash = ?1
`

// scopeguard:allow-unscoped: token_hash is the sha256 of a 256-bit bearer capability that itself authorizes
// access; a session is resolved before any Principal exists, so no user_id predicate is possible or meaningful at
// this lookup stage.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionWithUserByTokenHash = `-- name: GetSessionWithUserByTokenHash :one
SELECT sessions.id, sessions.user_id, sessions.created_at, sessions.last_used_at, users.role
FROM sessions
JOIN users ON sessions.user_id = users.id
WHERE sessions.token_hash = ?1
`

type GetSessionWithUserByTokenHashRow struct {
	ID         string
	UserID     string
	CreatedAt  string
	LastUsedAt string
	Role       string
}

// scopeguard:allow-unscoped: resolved before any Principal exists, keyed by the bearer token_hash capability; no
// user_id predicate is possible at this pre-auth lookup stage. The JOIN to users retrieves the role in one read so
// the middleware can construct a store.Principal without a second DB round-trip.
func (q *Queries) GetSessionWithUserByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionWithUserByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithUserByTokenHash, tokenHash)
	var i GetSessionWithUserByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Role,
	)
	return i, err
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :execrows
DELETE FROM sessions
WHERE last_used_at < ?1
   OR created_at < ?2
`

type PurgeExpiredSessionsParams struct {
	IdleCutoff     string
	AbsoluteCutoff string
}

// scopeguard:allow-unscoped: system housekeeping; the scheduler purges across all users by TTL cutoffs (idle and
// absolute), so there is no meaningful user context available and a user_id predicate would prevent cross-user
// expiry from working.
func (q *Queries) PurgeExpiredSessions(ctx context.Context, arg PurgeExpiredSessionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeExpiredSessions, arg.IdleCutoff, arg.AbsoluteCutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
