// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
	"database/sql"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings
WHERE setting_key = ?1
`

// Delete a setting by key.  No-op when the key does not exist.
func (q *Queries) DeleteSetting(ctx context.Context, settingKey string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, settingKey)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT setting_key, value, updated_at
FROM settings
WHERE setting_key = ?1
`

// Retrieve a single setting row by its exact key.
func (q *Queries) GetSetting(ctx context.Context, settingKey string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, settingKey)
	var i Setting
	err := row.Scan(&i.SettingKey, &i.Value, &i.UpdatedAt)
	return i, err
}

const listSettingsByPrefix = `-- name: ListSettingsByPrefix :many
SELECT setting_key, value, updated_at
FROM settings
WHERE setting_key LIKE ?1 || '%' ESCAPE '\'
ORDER BY setting_key
`

// List all settings whose key starts with @prefix, ordered by key. The caller
// must escape LIKE metacharacters (\, %, _) in @prefix; ESCAPE '\' then makes
// those escapes literal, so a prefix containing '_' or '%' matches literally
// rather than as a wildcard.
func (q *Queries) ListSettingsByPrefix(ctx context.Context, prefix sql.NullString) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettingsByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.SettingKey, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (setting_key, value, updated_at)
VALUES (?1, ?2, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
ON CONFLICT(setting_key) DO UPDATE
    SET value      = excluded.value,
        updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertSettingParams struct {
	SettingKey string
	Value      string
}

// Upsert a setting by key.  Inserts a new row or replaces value and
// updated_at when the key already exists.
func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.SettingKey, arg.Value)
	return err
}
