// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_data.sql

package db

import (
	"context"
)

const deleteUserData = `-- name: DeleteUserData :exec
DELETE FROM user_data
WHERE id = ?1
  AND user_id = ?2
`

type DeleteUserDataParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteUserData(ctx context.Context, arg DeleteUserDataParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserData, arg.ID, arg.UserID)
	return err
}

const getUserData = `-- name: GetUserData :one
SELECT id, user_id, value, created_at
FROM user_data
WHERE id = ?1
  AND user_id = ?2
`

type GetUserDataParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetUserData(ctx context.Context, arg GetUserDataParams) (UserDatum, error) {
	row := q.db.QueryRowContext(ctx, getUserData, arg.ID, arg.UserID)
	var i UserDatum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const insertUserData = `-- name: InsertUserData :exec

INSERT INTO user_data (id, user_id, value)
VALUES (?1, ?2, ?3)
`

type InsertUserDataParams struct {
	ID     string
	UserID string
	Value  string
}

// Scoped queries for the user_data exemplar table.
// Every SELECT/UPDATE/DELETE includes a user_id predicate so the row always
// comes from and is limited to the bound Scope. This pattern is the template
// that real domain tables must follow; the CI guard in scopeguard.go enforces
// it at build time.
//
// Parameters use sqlc named params (@name) per the house convention; the
// generated Params structs carry typed fields (ID, UserID, Value).
func (q *Queries) InsertUserData(ctx context.Context, arg InsertUserDataParams) error {
	_, err := q.db.ExecContext(ctx, insertUserData, arg.ID, arg.UserID, arg.Value)
	return err
}

const listUserData = `-- name: ListUserData :many
SELECT id, user_id, value, created_at
FROM user_data
WHERE user_id = ?1
ORDER BY created_at
`

func (q *Queries) ListUserData(ctx context.Context, userID string) ([]UserDatum, error) {
	rows, err := q.db.QueryContext(ctx, listUserData, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDatum
	for rows.Next() {
		var i UserDatum
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
