// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec

INSERT INTO users (id, email, display_name, password_hash, role, timezone, locale, language, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
`

type CreateUserParams struct {
	ID           string
	Email        string
	DisplayName  string
	PasswordHash string
	Role         string
	Timezone     string
	Locale       string
	Language     string
	CreatedAt    string
	UpdatedAt    string
}

// Queries for the users identity table.
// users is system-owned (no user_id column; it is the identity table from which per-user scope is derived) and is
// exempt from the scope guard.  All SELECT/UPDATE operations are therefore permitted without a user_id predicate.
//
// Parameters use sqlc named params (@name) per the house convention.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
		arg.Timezone,
		arg.Locale,
		arg.Language,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, password_hash, role, timezone, locale, language, created_at, updated_at
FROM users
WHERE email = ?1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Timezone,
		&i.Locale,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, password_hash, role, timezone, locale, language, created_at, updated_at
FROM users
WHERE id = ?1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Timezone,
		&i.Locale,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :execrows
UPDATE users
SET password_hash = ?1,
    updated_at    = ?2
WHERE id = ?3
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPasswordHash, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserProfile = `-- name: UpdateUserProfile :execrows
UPDATE users
SET display_name = ?1,
    timezone     = ?2,
    locale       = ?3,
    language     = ?4,
    updated_at   = ?5
WHERE id = ?6
`

type UpdateUserProfileParams struct {
	DisplayName string
	Timezone    string
	Locale      string
	Language    string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Timezone,
		arg.Locale,
		arg.Language,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
