//go:build e2e

package gateway

// scripted.go — ScriptedChatter for deterministic E2E testing (e2e build tag only).
//
// ScriptedChatter implements harness.Chatter and emits a deterministic sequence
// of streaming deltas, tool calls, and completion events per turn, driven by a
// JSON script fixture.  It is physically absent from the default binary.
//
// # Script fixture schema
//
// A fixture is a JSON object with a top-level "rules" array.  Each rule has a
// "match" and a "rounds" array:
//
//	{
//	  "rules": [
//	    {
//	      "match": {
//	        "contains": "create reminder",   // case-insensitive substring match
//	        "prefix":   "delete"             // case-insensitive prefix match
//	      },
//	      "rounds": [
//	        {
//	          "chunks": [
//	            { "textDelta": "Planning…", "delayMs": 5 },
//	            { "toolCall": { "name": "create_reminder", "arguments": {"title":"Buy milk","dueAt":"2026-06-15T09:00:00Z"} } },
//	            { "done": true }
//	          ]
//	        },
//	        {
//	          "chunks": [
//	            { "textDelta": "Done! I created the reminder.", "delayMs": 2 },
//	            { "done": true }
//	          ]
//	        }
//	      ]
//	    }
//	  ]
//	}
//
// Match semantics (evaluated case-insensitively against the latest user message):
//   - "contains": the user message contains the given substring.
//   - "prefix":   the user message starts with the given prefix.
//   - When both fields are non-empty the rule matches when EITHER condition holds.
//   - The first matching rule wins (rules are evaluated in order).
//
// Round selection is stateless: the round index equals the number of non-user
// (assistant or tool) messages that follow the latest user message in the
// ChatRequest history.  Round 0 is the first response; round 1 is the response
// after a tool result has been added to history; and so on.  This lets a
// multi-round tool loop terminate correctly without any mutable per-conversation
// state in the scripted provider.
//
// When no rule matches, or the round index exceeds the rule's rounds array, the
// provider emits a safe default reply (a short text delta + Done) rather than
// hanging, and logs a warning.

import (
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"log/slog"
	"os"
	"slices"
	"strings"
	"time"

	"github.com/qovira/qovira/internal/id"
)

// ── JSON fixture types ────────────────────────────────────────────────────────

// scriptFixture is the top-level schema for a script fixture JSON file.
type scriptFixture struct {
	Rules []scriptRule `json:"rules"`
}

// scriptRule is one entry in a fixture's rules array.
type scriptRule struct {
	// Match describes how to select this rule from the latest user message.
	Match scriptMatch `json:"match"`
	// Rounds is the ordered sequence of model responses; each round corresponds
	// to one Chat call on the same conversation turn.
	Rounds []scriptRound `json:"rounds"`
}

// scriptMatch describes the match condition for a rule.
// Contains and Prefix are OR-ed; an empty string means "not checked".
type scriptMatch struct {
	// Contains is a case-insensitive substring that must appear in the user message.
	Contains string `json:"contains,omitempty"`
	// Prefix is a case-insensitive prefix that the user message must start with.
	Prefix string `json:"prefix,omitempty"`
}

// scriptRound is one round of model response (one Chat call).
type scriptRound struct {
	// Chunks is the ordered list of Chunk descriptors to emit for this round.
	Chunks []scriptChunk `json:"chunks"`
}

// scriptChunk describes one Chunk to emit.  Exactly one of TextDelta, ToolCall,
// or Done should be meaningful per chunk (mirroring the Chunk type).
// DelayMs is the time in milliseconds to wait before yielding this chunk, so a
// turn can be observed mid-stream.
type scriptChunk struct {
	// TextDelta is non-empty for text-content chunks.
	TextDelta string `json:"textDelta,omitempty"`
	// ToolCall, when non-nil, describes a tool call to emit.  The ID is
	// auto-generated by ScriptedChatter if not explicitly provided.
	ToolCall *scriptToolCall `json:"toolCall,omitempty"`
	// Done marks the terminal chunk for this round.
	Done bool `json:"done,omitempty"`
	// DelayMs is the number of milliseconds to sleep before yielding this chunk.
	// Keep values small in fixtures (e.g. 1–5 ms) to keep tests fast.
	DelayMs int `json:"delayMs,omitempty"`
}

// scriptToolCall describes the tool call fields within a scriptChunk.
type scriptToolCall struct {
	// ID is the tool call ID.  When empty, one is auto-generated.
	ID string `json:"id,omitempty"`
	// Name is the tool name (e.g. "create_reminder").
	Name string `json:"name"`
	// Arguments is the raw JSON arguments object.  Provided as json.RawMessage
	// so any valid JSON object is accepted without an intermediate type.
	Arguments json.RawMessage `json:"arguments,omitempty"`
}

// ── ScriptedChatter ───────────────────────────────────────────────────────────

// ScriptedChatter implements harness.Chatter with a deterministic scripted
// response sequence loaded from a JSON fixture.  It is safe for concurrent use.
type ScriptedChatter struct {
	rules  []scriptRule
	logger *slog.Logger
}

// NewScriptedChatterFromJSON constructs a ScriptedChatter from raw JSON fixture bytes.
// Returns an error if the JSON is malformed.
func NewScriptedChatterFromJSON(data []byte) (*ScriptedChatter, error) {
	var fix scriptFixture
	if err := json.Unmarshal(data, &fix); err != nil {
		return nil, fmt.Errorf("scripted: parse fixture: %w", err)
	}
	return &ScriptedChatter{
		rules:  fix.Rules,
		logger: slog.Default(),
	}, nil
}

// NewScriptedChatterFromFile constructs a ScriptedChatter by reading a fixture
// file from the given path.
func NewScriptedChatterFromFile(path string) (*ScriptedChatter, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("scripted: read fixture %q: %w", path, err)
	}
	return NewScriptedChatterFromJSON(data)
}

// Chat implements harness.Chatter.  It selects the matching rule and round
// index from req's message history, then returns an iterator that yields each
// chunk (honouring per-chunk DelayMs and ctx cancellation).
//
// Rule and round selection is entirely stateless — no per-conversation state is
// kept in ScriptedChatter.  See the package-level comment for the algorithm.
func (sc *ScriptedChatter) Chat(ctx context.Context, req ChatRequest) (iter.Seq2[Chunk, error], error) {
	chunks := sc.selectChunks(req)
	seq := func(yield func(Chunk, error) bool) {
		for _, sc2 := range chunks {
			// Honour DelayMs before yielding — this lets a consumer observe a
			// turn mid-stream (e.g. Playwright checking SSE events mid-turn).
			if sc2.DelayMs > 0 {
				delay := time.Duration(sc2.DelayMs) * time.Millisecond
				select {
				case <-ctx.Done():
					yield(Chunk{}, ctx.Err())
					return
				case <-time.After(delay):
				}
			}
			// Check cancellation even when DelayMs == 0.
			select {
			case <-ctx.Done():
				yield(Chunk{}, ctx.Err())
				return
			default:
			}

			chunk := toChunk(sc2)
			if !yield(chunk, nil) {
				return
			}
		}
	}
	return seq, nil
}

// ── helpers ───────────────────────────────────────────────────────────────────

// selectChunks picks the scriptChunks to emit for this Chat call.
// It is the core of the stateless round-selection logic.
func (sc *ScriptedChatter) selectChunks(req ChatRequest) []scriptChunk {
	// 1. Find the latest user message index.
	latestUserIdx := -1
	for i, msg := range slices.Backward(req.Messages) {
		if msg.Role == "user" {
			latestUserIdx = i
			break
		}
	}
	if latestUserIdx < 0 {
		sc.logger.Warn("scripted: no user message in request; emitting safe default")
		return defaultChunks()
	}

	latestUserContent := req.Messages[latestUserIdx].Content

	// 2. Compute round index = number of assistant messages that appear AFTER the
	//    latest user message in the history.  Each assistant message (whether or
	//    not it carries tool calls) represents one completed model round; the tool
	//    result messages that follow are part of the same round exchange and do not
	//    advance the counter.  This gives:
	//      - 0 assistant msgs after user → round 0 (first model response)
	//      - 1 assistant msg  after user → round 1 (after a tool-result loop)
	//      - etc.
	roundIdx := 0
	for i := latestUserIdx + 1; i < len(req.Messages); i++ {
		if req.Messages[i].Role == "assistant" {
			roundIdx++
		}
	}

	// 3. Find the first matching rule.
	for _, rule := range sc.rules {
		if matchesRule(rule.Match, latestUserContent) {
			if roundIdx >= len(rule.Rounds) {
				sc.logger.Warn("scripted: round index out of range; emitting safe default",
					"latestUserContent", latestUserContent,
					"roundIdx", roundIdx,
					"rulesLen", len(rule.Rounds),
				)
				return defaultChunks()
			}
			return rule.Rounds[roundIdx].Chunks
		}
	}

	sc.logger.Warn("scripted: no matching rule; emitting safe default",
		"latestUserContent", latestUserContent,
	)
	return defaultChunks()
}

// matchesRule reports whether the rule's match condition is satisfied by the
// given user message.  Matching is case-insensitive.  When both Contains and
// Prefix are non-empty, either condition suffices.
func matchesRule(m scriptMatch, userMsg string) bool {
	lower := strings.ToLower(userMsg)
	if m.Contains != "" && strings.Contains(lower, strings.ToLower(m.Contains)) {
		return true
	}
	if m.Prefix != "" && strings.HasPrefix(lower, strings.ToLower(m.Prefix)) {
		return true
	}
	return false
}

// toChunk converts a scriptChunk into a gateway Chunk for emission.
func toChunk(sc scriptChunk) Chunk {
	if sc.ToolCall != nil {
		callID := sc.ToolCall.ID
		if callID == "" {
			callID = id.New()
		}
		args := sc.ToolCall.Arguments
		if args == nil {
			args = json.RawMessage(`{}`)
		}
		return Chunk{
			ToolCall: &ToolCall{
				ID:        callID,
				Name:      sc.ToolCall.Name,
				Arguments: args,
			},
		}
	}
	return Chunk{
		TextDelta: sc.TextDelta,
		Done:      sc.Done,
	}
}

// defaultChunks returns the safe-default chunk sequence emitted when no rule
// matches or the round index is out of range.
func defaultChunks() []scriptChunk {
	return []scriptChunk{
		{TextDelta: "[scripted provider: no matching script for this turn]"},
		{Done: true},
	}
}
