import js from "@eslint/js";
import svelte from "eslint-plugin-svelte";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  ...svelte.configs["flat/recommended"],
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      parserOptions: {
        projectService: {
          // Config files not covered by the SvelteKit-generated tsconfig:
          // svelte.config.js (JS) and vitest.config.ts.
          // vite.config.ts is already included via .svelte-kit/tsconfig.json.
          // service-worker.ts is excluded by .svelte-kit/tsconfig.json (it uses
          // the webworker lib instead of DOM); add it here so ESLint can parse it.
          allowDefaultProject: ["*.config.js", "vitest.config.ts", "src/service-worker.ts"],
        },
        tsconfigRootDir: import.meta.dirname,
        extraFileExtensions: [".svelte"],
      },
    },
  },
  {
    files: ["**/*.svelte", "**/*.svelte.ts"],
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
      },
    },
  },
  {
    // tseslint.config() is deprecated in favour of ESLint's own defineConfig(),
    // which ships in ESLint 10. We are pinned to ESLint 9 for now; suppress
    // the rule on this file only until we upgrade eslint.
    files: ["eslint.config.js"],
    rules: {
      "@typescript-eslint/no-deprecated": "off",
    },
  },
  {
    // schema.d.ts is generated by openapi-typescript — do not lint it.
    // The generated index signatures ([name: string]: unknown) are correct for
    // the OpenAPI headers map and cannot be changed without re-generating.
    ignores: [
      "build/",
      ".svelte-kit/",
      "dist/",
      "node_modules/",
      "src/lib/api/schema.d.ts",
      // Paraglide-JS generated i18n runtime — compiled by pnpm compile:i18n
      "src/lib/paraglide/",
    ],
  },
);
